// <auto-generated />
using System;
using Infrastructure.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.EF.Migrations
{
    [DbContext(typeof(DMSContext))]
    partial class DMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationCore.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HashedPassword");

                    b.Property<DateTime>("RegisterationDate");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ApplicationCore.Entities.DatabaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConnectionString");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Databases");
                });

            modelBuilder.Entity("ApplicationCore.Entities.EntityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<int>("DbId");

                    b.Property<long>("EndRange");

                    b.Property<string>("EntityType");

                    b.Property<long>("StartRange");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DbId");

                    b.HasIndex("EndRange")
                        .IsUnique();

                    b.HasIndex("StartRange")
                        .IsUnique();

                    b.ToTable("EntityRecords");
                });

            modelBuilder.Entity("ApplicationCore.Entities.EntityRecord", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Client", "client")
                        .WithMany("AccessedRanges")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApplicationCore.Entities.DatabaseItem", "database")
                        .WithMany("ContainedRanges")
                        .HasForeignKey("DbId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
